# Source: https://github.com/makerdao/maker-otc

sudo: required
dist: trusty

language: node_js
node_js: "5.1"

services:
  docker

git:
  submodules: false

env:
  - TEST=dapple

before_install:
  - id
  - if [ $TEST = "dapple" ]; then docker pull rainbeam/dapple-minimal && docker images; fi
  - cp .travis.dapplerc $HOME/.dapplerc

install:
  - if [ $TEST = "dapple" ]; then git submodule update --init --recursive; fi
  - if [ $TEST = "npm"  ]; then npm set progress=false && npm install; fi

script:
  - if [ $TEST = "dapple" ]; then ./.travis.dapple-docker-entry test; fi
  - if [ $TEST = "npm" ]; then npm test; fi
